services:
  web:
    build: .
    command: ["true"]
    environment:
      DB_ENGINE: ${DB_ENGINE}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    volumes:
      - .:/usr/app    
  web_migrate:
    extends:
      service: web
    command: > 
      sh -c "python porrasite/manage.py makemigrations && 
             python porrasite/manage.py migrate"
    depends_on:
      db:
        condition: service_healthy
  web_loaddata:
    extends:
      service: web
    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    command: >
      sh -c "python porrasite/manage.py loaddata euro2016 &&
             (python porrasite/manage.py createsuperuser --noinput || true) &&
             (echo \"from django.contrib.auth.models import User; User.objects.get_or_create(username='zupo', defaults={'email':'email'})[0].set_password('password')\" | python porrasite/manage.py shell || true)"
    depends_on:
      web_migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
  web_run:
    extends:
      service: web
    command: python porrasite/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      web_loaddata:
        condition: service_completed_successfully
      db:
        condition: service_healthy

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
